name: Publish Docker image   # workflow名称，可以在Github项目主页的【Actions】中看到所有的workflow

on:   # 配置触发workflow的事件
  push:   # 当有push操作时触发
    branches:   # 只有在master分支上push才触发
      - 'master'

jobs:  # workflow中的job

  push_to_registry:  # job的名字
    name: Push Docker image to Docker Hub   # job的名称，用于显示在workflow页面上
    runs-on: ubuntu-latest   # job运行的基础环境，使用最新的ubuntu镜像

    steps:  # 一个job由一个或多个step组成
      - name: Check out the repo   # 拉取代码
        uses: actions/checkout@v2   # 使用官方提供的checkout action

      - name: Log in to Docker Hub   # 登录到Docker Hub
        uses: docker/login-action@v1   # 使用docker提供的登录action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # 从Github的secrets中获取用户名
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # 从Github的secrets中获取密码

      - name: Extract metadata (tags, labels) for Docker   # 从代码中提取镜像信息
        id: meta   # 用于后续步骤引用该步骤的输出
        uses: docker/metadata-action@v4   # 使用docker提供的metadata action
        with:
          images: codeare/chatgpt_academic   # 镜像名称

      - name: Build and push   # 构建和推送镜像
        id: docker_build   # 用于后续步骤引用该步骤的输出
        uses: docker/build-push-action@v4   # 使用docker提供的build-push action
        with:
          context: .   # Dockerfile所在的路径
          push: true   # 是否推送镜像到Docker Hub
          tags: |
            codeare/chatgpt_academic:latest
            codeare/chatgpt_academic:${{ github.ref }}
            codeare/chatgpt_academic:$(echo ${{ github.sha }} | cut -c1-7)
            codeare/chatgpt_academic-arm64:latest
            codeare/chatgpt_academic-arm64:${{ github.ref }}
            codeare/chatgpt_academic-arm64:$(echo ${{ github.sha }} | cut -c1-7)
          platforms: |
            linux/amd64 
            linux/arm64 
