name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync Fork
        uses: wei/git-sync@v1
        with:
          source_repo: https://github.com/binary-husky/chatgpt_academic
          source_branch: master
          destination_repo: https://github.com/dandeliono/chatgpt_academic
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
