name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Fork
        uses:  tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: binary-husky 
          head: master
          base: master
